version: '3.3'

services:
  eureka:
    build:
      context: ./eureka
      dockerfile: Dockerfile
    image: eureka
    container_name: eureka
    ports:
      - 8761:8761
    network_mode: host

  pricing:
    build:
      context: ./pricing
      dockerfile: Dockerfile
    depends_on:
      - eureka
    image: pricing
    container_name: pricing
    ports:
      - 8082:8082
    network_mode: host

  boogle:
    build:
      context: ./maps
      dockerfile: Dockerfile
    image: boogle
    container_name: boogle
    ports:
      - 9191:9191
    network_mode: host

  vehicles:
    build:
      context: ./vehicles
      dockerfile: Dockerfile
    depends_on:
      - eureka
      - boogle
      - pricing
    image: vehiclesapi
    container_name: vehiclesapi
    ports:
      - 8080:8080
    network_mode: host

